title: Checking the Certutil Download
id: 9304309c-1008-4eda-9f6d-c505c049693b
status: test
description: Detecting the certutil download
author: Bhagavan Bollina
date: 2025-06-01
modified: 2025-06-01
logsource:
  product: windows
  service: sysmon
detection:
  selection:
    EventID: 1
    CommandLine|contains|all:
      - '-urlcache'
      - '-split'
      - '-f'
    Image|endswith: 'certutil.exe'
  condition: selection
fields:
  - CommandLine
  - Image
  - ParentImage
  - User
  - CurrentDirectory
falsepositives:
  - Legitimate use of certutil for certificate management
level: medium
tags:
  - attack.credential_access
  - attack.t1110
references:
  - https://www.cybereason.com/blog/certutil-exe-abuse
  - https://www.cybereason.com/blog/certutil-exe-abuse-part-2
